### ISSUE TITLE
(Naomi Stage 5) Naomi fails to fall completely with a falling platform

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#100]
The large falling platform at the end of the first room after the first stage 5 checkpoint (which transitions into the next area below), left me paused in midair near the bottom of the screen, rather than _actually_ falling into the next area. I remained there briefly until I pressed a movement key, which caused gravity to take over and finish the job.

(On retesting, apparently you continue to fall again after this pause, if you just wait about a second or so? Though it does seem reproducible, at least.)

**Comment by Kayinnasaki** [comment]
I assume that's just loading lag. Can't really fix that.

**Comment by DracoOmega** [comment]
This happens before Naomi's feet have even reached the bottom of the screen, though. If it _is_ loading lag, shall I assume it's non-trivial for the loading pause to not happen until you appear to actually be falling _off_ the screen, rather than hovering a couple feet above the edge? It's not a major issue either way, of course, but would probably be a little nicer.
