### ISSUE TITLE
(Naomi Stage 4) Alcyoneus appeared to get stuck in foot-stomping phase without foot injury

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#101]
On one attempt, I had done enough damage to Alcyoneus's head to require hitting his foot next, but he had not shot any cannonballs for me to reflect (and thus I couldn't hurt his foot). He just started to stomp over and over and over again, not doing any other attacks (and thus making it impossible to injure him). The next weakspot you need to hit did not yet exist, and he wouldn't perform the attack that would allow me to open it.

It's possible this was just _really_ bad RNG (though even then, it's potentially a problem if it can APPEAR as though the boss battle has gotten 'stuck'). It didn't happen on subsequent attempts where I finished the head before reflecting both cannonballs. He would add the stomp attack to his repertoire once the head was sufficiently damaged, but still mix in other attacks, including the cannonball.

The only difference that obviously comes to mind between the time I got 'stuck' and later attempts is that the first time, the boss had moved about as far left as it seems willing to ever move in this phase? Possibly that affects something, and it won't use the cannonball attack from that range?

**Comment by Kayinnasaki** [comment]
Alcyoneus doesn't have RNG for his basic attacks. Even at his closest position to the wall you should be able to get ifar enough to trigger the cannon.

**Comment by DracoOmega** [comment]
You know, in all this length of time, I never realized that you had to stand a certain distance away from him to trigger it. I actually did just think it was random. It's quite possible that, with the wall so close, I simply never backed entirely up to it (since I had no idea that would actually be productive) and with him no longer using the cross attack, he just stomped continuously.

So maybe not a bug, though it does make me a little concerned that new players might end up in the same situation and not realize what they're supposed to do?

**Comment by Kayinnasaki** [comment]
Still gonna close because there really aren't many other options here. This was the first time anyone got caught up on that so I'm not gonna worry too much.
