### ISSUE TITLE
(Naomi Stage 4) Text about hitting Alcyoneus' heel is potentially misleading

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#104]
Just a minor quibble, but when I first saw Naomi say "I can't hit it from the front.", it seemed odd to me since I HAD been hitting it [Alcyoneus] from the front all this time, and in fact had to hit it several more times from its front to make it start stomping and expose the heel.

It might be better if the message was more specific that you can't hit its _heel_ from the front.

**Comment by Kayinnasaki** [comment]
changed to "I can't hit the heel from the front!"
