### ISSUE TITLE
Can Access Trevor Stage 2 Without Having Done Stage 1

### ISSUE THREAD

**Issue by TalentedJuli** [Kayinnasaki/BepIssueTracker#109]
If I go to St. Brennan Cathedral on Naomi's level selection screen, choose the level, then switch to Trevor using Left/Right, it lets me play through the level as though I'm on his path.
![brennan](https://cloud.githubusercontent.com/assets/13173892/14059509/c2262126-f2ff-11e5-9c0e-dc67e9c434f3.jpg)

**Comment by Kayinnasaki** [comment]
Seems to not be an issue anymore? Tentatively closing, but expecting this to pop up again
