### ISSUE TITLE
Windowed mode forced to be in foreground.

### ISSUE THREAD

**Issue by Trynant** [Kayinnasaki/BepIssueTracker#110]
BE:P is covering all my windows :(

System Specs:
OS: Windows 8.1 Enterprise
Processor: Dual-Core CPU (Intel i7 4790K , 8 CPUs ~4.0 GhZ)
Memory: 16 GB RAM
Graphics: NVDIA GTX 760
DirectX 11

**Comment by Kayinnasaki** [comment]
Unreproducible and probably not something I could effect or fix
