### ISSUE TITLE
Various oddities with Sinlin's attacking behavior

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#111]
Some of these are definitely bugs and some are possibly not, but after two hours of jumping around like a madman to track down the harder-to-replicate ones, I'm just going to be comprehensive with my description of how the mechanics currently work; it's your call what is deliberate and what is an oversight.

(I apologize for grouping so many issues into one ticket, but many are related in ways that make them easier to explain together)

---

**Issue 1:** It is impossible to attack during Sinlin's 'reverse movement direction' transition animation. The attack button simply does nothing at all when she's in this state. Since releasing the movement key _does_ cut the transition animation short, tapping movement and then firing works, but holding movement and pressing fire doesn't. This seems wrong (and definitely causes attacks to fail to work when you'd expect them to work).

---

**Issue 2:** The 'cooldown period' between attacks is counterintuitively based on a fixed interval of time from when Sinlin _starts_ attacking, and not when her last shot was fired, and does not vary based on the firing speed of her current spell. Some examples of the consequences of this:

Gunner, when held, fires several times as fast as this cooldown period. This means that if you fire just one projectile, release fire, and press it again, nothing will happen (attack is still on 'cooldown', despite the fast fire rate of projectiles). But if you had held fire for a little while _before_ releasing it, you can press fire again immediately after releasing it and new shots will come out.

With a spell that has a slower attack rate (such as Renka), this can allow you to fire faster than the normal firing rate, by periodically re-pressing attack when the cooldown period is up. More explicitly, if you hold attack, the spell will fire every X frames. Pressing attack will initiate a new attack so long as Y frames have passed from the last time Sinlin started attacking. After the cooldown period is up (you've been holding attack for a little bit), you can release and re-press attack to 'sidestep' the normal delay between shots (since this is now a 'new attack' and the fire button doesn't actually care when a projectile last came out).

This may be essentially intentional, although I think the behavior with Gunner (where attack fails to work even when you are pressing it less often than Sinlin already demonstrates she can fire) feels clunky and unintuitive. It's a bad feeling when you expect buttons to do something and they don't.

But regardless, this 'cooldown period' is central to the issues which follow.

---

**Issue 3:** If you crouch and press fire while your attack is on cooldown, the game will make a distinct swishing sound and Sinlin will begin her 'finger-wagging' attack animation, but no shots will ever fire, no matter how long you hold this animation.

---

**Issue 4:** There is inconsistent behavior with holding down fire while your attack is on cooldown,  depending on whether you are airborne or not. If you press and hold fire during the cooldown period while on the ground, nothing will ever happen. No animations, no actions, no shots even if the button remains depressed once the cooldown period is up. If you do this in the _air_ instead, Sinlin will begin firing as soon as the cooldown period ends.

---

**Issue 5: (Critical)** If you tap fire while airborne, during the cooldown period, it locks your movement until the cooldown period ends. Even if you release the button, you cannot reverse your aerial momentum until this time has passed. Even if you land on the ground again, you still cannot move at all.

Once the cooldown period ends, there is a one-frame flash of the attack animation (visible by the magic circle in the air), though this is too brief to actually produce a projectile. I think this implies the game is somehow sticking you in 'attack mode' (where you normally cannot move), even if you release the button and never appeared to attack at all. But, suffice it to say, anything that 'randomly' locks the player's midair movement is really bad.

---

**Issue 6:** Probably related to the above. This one was a pain in the butt to figure out how to reproduce, but I'm _mostly_ sure I've got this right (or am very close to it).
- While in midair and your attack is on cooldown, tap and release the attack button
- At the very frame that the one-frame flash of attack would happen from the previous time you tapped the button, press and hold attack

This will cause the spell circle to manifest in midair and projectiles to start firing out of it instead of Sinlin (as gravity pulls her away from it). It even allows them to fire in the opposite direction that Sinlin is facing. This midair spell circle only lasts long enough to fire a couple shots before disappearing, but afterward Sinlin's attack speed on the ground will be doubled for so long as you hold the attack button.

**Comment by Kayinnasaki** [comment]
Should mostly be cleaned up
