### ISSUE TITLE
Pressing fire while Sinlin is hovering causes unusual behavior

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#112]
This is partially a visual glitch and partially a behavioral oddity.

While Sinlin is performing her air hover, if you press attack with any weapon but the forbidden dagger (tap or hold, doesn't matter) Sinlin will descend gracefully with the magical platform still beneath her and it will even remain while on the ground without consuming energy. However, it turns out that this is basically the trajectory of her normal jump, so the bug is showing the visual of the platform beneath her instead of her abandoning the platform altogether.

However, there is an extra oddity in that the attack attempt does nothing at all, except with the forbidden dagger or chakram. You won't fire, but will still break your hover (with the abovementioned graphical glitch).

The forbidden dagger exhibits neither of these behaviors (you remain hovering and attack while hovering), chakram allows you to fire but causes the false visual on your descent, and other weapons fail to attack while causing the false visual on your descent.

**Comment by Kayinnasaki** [comment]
This has... oddly been begged to not be removed for a long time now.
