### ISSUE TITLE
(Sinlin Stage 5) Can unexpectedly remove powerups in the room post-elevator

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#113]
This may not be strictly a bug, but still unexpected behavior. If you fire Sinlin's gunner special from the top of the first elevator, the wave will pass out of the elevator room and into the room beyond and since a bunch of candles are all lined up neatly, will break a bunch of objects in the next area. This resulted in health/energy flying at me from off-screen (for unclear reasons at first), but also removes the renka powerup completely, since there's no way to reach it before it expires.

I believe it also spawned several enemies 'prematurely', since I seemed to recall being shot at from a greater distance than normal when I entered this room after doing this then when I did not. This is more time-consuming to reproduce and I haven't tested it thoroughly.

This is maybe not 'wrong' since they are technically connected areas and the wave just keeps on going, but at least to me, when two rooms have a non-scrolling transition between then, you don't expect to be able to affect what's going on in the next one, particularly at this kind of insane range (does the wave attack have no maximum range at all?)

**Comment by Kayinnasaki** [comment]
distance limit put on lanterns being broken
