### ISSUE TITLE
Naomi: Chapter 4: Vayn/Donovan dialogue can be re-triggered, locking Naomi out of her attack

### ISSUE THREAD

**Issue by Kishkish** [Kayinnasaki/BepIssueTracker#12]
Date: 2015.05.20

Steps to Reproduce:
1. Progress to Chapter 4 with Naomi.
2. Advance to the top of the staircase where Vayn and Donovan have their conversation to create a checkpoint.
3. Die.
4. After respawning at the checkpoint, go all the way back down the stairs.
5. Observe.

Result:
Vayn and Donovan are gone, but their dialogue is triggered again. This also prevents Naomi from attacking, and she is stuck in this state until she dies again.

Expected Result:
The trigger for Vayn and Donovan's dialogue should be gone when Naomi spawns beyond it.

**Comment by Kayinnasaki** [comment]
Stairs down have been blocked. The simplest solution!
