### ISSUE TITLE
Naomi: Chapter 5: Attack is not turned off during opening dialogue

### ISSUE THREAD

**Issue by Kishkish** [Kayinnasaki/BepIssueTracker#13]
Date: 2015.05.20

Steps to Reproduce:
1. Progress to Chapter 5 with Naomi.
2. When Naomi is speaking to Trevor at the beginning, advance the text.
3. Observe Naomi's sprite.

Result:
Naomi's attack is not turned off, so when the player must make her slash the air to advance the text. Just looks weird!

Expected Result:
Naomi's attack should be turned off until she walks through the front door of the cathedral.

**Comment by Kishkish** [comment]
![ch5cutsceneattack](https://cloud.githubusercontent.com/assets/12528330/7725118/861020a8-feac-11e4-8e97-221642b93eba.png)

**Comment by Kayinnasaki** [comment]
Fixed.
