### ISSUE TITLE
Naomi: Chapter 5: No visual continuity when entering cathedral

### ISSUE THREAD

**Issue by Kishkish** [Kayinnasaki/BepIssueTracker#14]
Date: 2015.05.20

Steps to Reproduce:
1. Progress to Chapter 5 with Naomi.
2. Walk into the cathedral through the front door.
3. Observe Naomi's surroundings and position after the screen transition.

Result:
The door Naomi came in through is not visible. It could be in the wall on the left, but she spawns suddenly in the center of the room.

Expected Result:
After the player goes through the doorway, they should be able to see it from the next area.

![ch5doora](https://cloud.githubusercontent.com/assets/12528330/7725207/38bc6b94-fead-11e4-911d-dd3b0359f0ba.png) ![ch5doorb](https://cloud.githubusercontent.com/assets/12528330/7725208/3bcef2b6-fead-11e4-8e6e-5e5d98d376fa.png)

**Comment by Kayinnasaki** [comment]
That room is 'behind' the start room  and the door is on the '4th wall'. I could change the lighting style in the room to hint at that? (having light flood  in and mimick the door frame and spread from there?

**Comment by Kishkish** [comment]
That would probably get it across! Or you could draw a dotted outline of a door like in Monster World IV, but that might be too cute for this game. ♥

**Comment by Kayinnasaki** [comment]
"fixed"
