### ISSUE TITLE
Naomi: Chapter 5: Non-progression after falling into pit

### ISSUE THREAD

**Issue by Kishkish** [Kayinnasaki/BepIssueTracker#15]
Date: 2015.05.20

Steps to Reproduce:
1. Progress to Chapter 5 with Naomi.
2. Fall into the pit in the attached image.
3. Observe.

Result:
Naomi neither dies nor transitions to a different area; she just falls off the edge of the screen. The player can still move left and right, but they cannot jump out or hit screen transitions to the left or right. The only way out is to restart the stage.

Expected Result:
Naomi should die or reach a different area after falling, or the pit should be blocked off.

![ch5pit](https://cloud.githubusercontent.com/assets/12528330/7725258/c4238b9a-fead-11e4-8aaf-0e6c880227e8.png)

**Comment by Kayinnasaki** [comment]
Death Marker added. Fixed
