### ISSUE TITLE
initial playtest text dump (gl parsing this kayin)

### ISSUE THREAD

**Issue by tijit** [Kayinnasaki/BepIssueTracker#17]
stuff

~~opening room: incorrect depth on left pillar tiles~~
_fixed_

dialogue scrolling: change pls!

slopes bug? (move faster with a jump press?) (get jumping horizontal velocity, but stuck to the slope)

bat enemy going back to "rest" state in the ground

~~you can move up and down ramps during hit stun using up/down (issue submitted)~~
_fixed_
## 

s1
## 

s2

~~piercing sword guy can get up to a higher platform?~~
_Probably fixed? If it was the one in the water right after Vayn?_
## 

s3

~~can stand on the side of water pit right after first checkpoint (w archer & bomber)~~
_fixed_

~~dialogue: two gets?~~
## _fixed_

s4

~~multiple enemy blood particles not showing (intentional?)~~
_In tracker_

~~drop kick miniboss can roll forever when up against gate~~
_fixed_

~"stuttering"~
_Fixed_

pointless boss run

boss double bombs dont bounce high enough? (kinda luckish whetherh you can destroy them in the air)

boss last phase: not apparent when broken cross is a platform or should damage you, & hitbox is v strange

~~you can clip through cross by attacking before dialogue starts (was unable to reproduce this), can slide down it too~~
_Minor, so I'm not going to try and chase this_

boss has too much rng? titan can use foot stomp before bombs have eroded his foot armour
## _Stomp happens when face is max damaged for the phase. This is as intended_

s5

~~glitch through the 1st vertical transition by damage boosting TO THE RIGHT near the top of the slope, end up in a later room? (this room isnt connected to the main map, looks like its where Big Sword Man goes, he mentions a lot of undead in the basement) also cant seem to reliable walk down the stairs here~~
_fixed!_

~~drop kick sequence break (intentional?)~~
~~,then another one~~
_intentional_

~~sequence with 2 shooty guys in the room w lots of gargoyles - one of the shooty guys can land in wrong spot (if he is damaged (?)) (ok never mind maybe its random)~~
*Fixed. Or well, changed. First iron gunner doesn't jump back much.

~~drop that is probably supposed to be lethal in section with bombers & archers (incomplete stage?)~~ (issue already submitted)
_and fixed!_

**Comment by Kayinnasaki** [comment]
Closed for cleanness. Most additional things are suggestions or minor. All still up for consideration though.
