### ISSUE TITLE
Chapter 1: Audio: Cut scene audio persists on map screen

### ISSUE THREAD

**Issue by Kishkish** [Kayinnasaki/BepIssueTracker#19]
Date: 2015.05.21
Reproduction Rate: 2/2

Steps to Reproduce:
1. Complete Chapter 1 as Naomi.
2. When the cut scene before Chapter 2 begins, press C to skip it.
3. On the map screen, observe the audio.

Result:
After exiting to the map screen, sound effects from the cut scene continue to play.

Expected Result:
The cut scene audio should cease upon skipping it.

**Comment by Kayinnasaki** [comment]
Fixed.
