### ISSUE TITLE
Chapter 2: Audio: A garbled sound plays when trying to pick up a 1-up with infinite lives

### ISSUE THREAD

**Issue by Kishkish** [Kayinnasaki/BepIssueTracker#20]
Date: 2015.05.21
Reproduction Rate: 3/3

Steps to Reproduce:
1. Start a new game and select Global or Standard difficulty.
2. Progress to Chapter 2.
3. At the checkpoint, destroy the breakable brick to reveal the 1-up (see attached image).
4. Attempt to collect the 1-up.
5. Observe the audio.

Result:
The 1-up cannot be collected, and a persistent garbled sound plays as long as the player sprite is touching it.

Expected Result:
In modes with infinite lives, 1-ups should be replaced with different items, removed, or at least be able to be picked up without any adverse effects.

![st2-1up](https://cloud.githubusercontent.com/assets/12528330/7743585/192357bc-ff51-11e4-8ecb-6593fd4c18cd.png)

**Comment by Kayinnasaki** [comment]
Weird! I tested this and had 1-ups set to fill health and energy. What a pain.

**Comment by Kishkish** [comment]
I tried it without full health/purple stuff, and they do get refilled when you touch the 1-up...but it still hangs around rather than disappearing, and the crazy sound still plays.

**Comment by Kayinnasaki** [comment]
Either way, will be fixed in the next revision.
