### ISSUE TITLE
Naomi can revisit Sinlin's section of chapter 3, causing some issues

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#22]
If you walk all the way to the left after reaching the fallen Ruby Knight past the Fairy Queen, you will eventually make it into the section of chapter 3 that only Sinlin can normally see. The camera doesn't scroll at first, but if you keep walking left offscreen long enough, the screen will still eventually transition and put you in the other part of the level, complete with monsters (but without music). If you then go back to the right, the level-end cutscene between Sinlin and Naomi does not display properly.

**Comment by Kayinnasaki** [comment]
Fixed!
