### ISSUE TITLE
Several issues with Sinlin chapter 3

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#23]
The message suggesting sliding through the passage near the level start is still displayed when you approach the passage as Sinlin.

Naomi seems oddly static during their interactions (I don't know if this is just incomplete?)

Sinlin can opt for Naomi's final segment of chapter 3, which seems a little odd, and results in you fighting the Fairy Queen and then the Ruby Knight immediately afterwards anyway. Is this deliberate? (It feels slightly confusing to me, if it is)

**Comment by Kayinnasaki** [comment]
To the last part, yes it is deliberate. You have to play through as Naomi first, so I feel like if the player opts for the top path, they should be unsurprised by what they get.

**Comment by Kayinnasaki** [comment]
Either way, fixed up.
