### ISSUE TITLE
Bomber powerup during Sinlin chapter 4 boss fight is invisible

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#24]
The one immediately below where the fight starts.

I know the room is dark, but if you manage to turn the lights on without picking the bomber spell up, there is still absolutely nothing visible, against a lit background, yet you gain the spell stepping into that spot anyway.

**Comment by Kayinnasaki** [comment]
Oh shit I forgot that I bumped into this but never fixed it.

**Comment by Kayinnasaki** [comment]
Fixed (and made the right spell -- gunner)
