### ISSUE TITLE
Somehow survived getting knocked off the screen by Sinlin chapter 1 boss

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#26]
I probably can't describe this one very usefully, but I got knocked right by fireballs while in the upper-right part of the screen, as the boss was dying. And despite falling off the edge of the screen and all the way down, didn't die. Eventually the 'chapter complete' text came up and the screen scrolled right to reveal part of my sprite stuck in the middle of the (ordinarily fatal) water.

**Comment by Kayinnasaki** [comment]
Fixed!
