### ISSUE TITLE
Falling into pit next to last pre-boss checkpoint in Naomi chapter 5 is not an instakill

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#29]
If you fall straight down the hole immediately to the right of the final checkpoint, you sometimes appear to land somewhere on the stage below (though the camera doesn't move), and you can even hear the skeletons start to crawl out of their pit. Death usually follows soon enough, but probably this is not intended behavior.

**Comment by Kayinnasaki** [comment]
Fixed!
