### ISSUE TITLE
Entering Trevor chapter 1 sometimes glitches?

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#31]
This might have to do with order of events. I started the chapter and the intro scene played just fine. Then I later left it to look at the tutorial, and then returned afterward (was still only on the first checkpoint of chapter 1). But when the level started, it merely showed the corner of town where the manticore was sitting, and the camera refused to move from there. I could control Trevor, but not see anything around him. Leaving and re-entering the stage showed the intro cutscene and everything was fine again.

**Comment by Kayinnasaki** [comment]
should be fixed due to a lot of other fixes.
