### ISSUE TITLE
Save file playtime display seems very wrong

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#34]
Or I'm just horribly misinterpreting it. Because it was something like 1:40 one day, then ~7:00 the next - which seemed a bunch more than I thought I played - but then today it listed ~40:00 which is certainly WAY more additional hours than I played yesterday.

**Comment by Kayinnasaki** [comment]
It shows seconds, so that might be whats getting thrown off? does 40 minutes sound right?

**Comment by DracoOmega** [comment]
40 minutes is way too low. It's like... at least 6 hours? Maybe slightly more, but definitely in that ballpark.

**Comment by DracoOmega** [comment]
There's definitely other weirdness here. The hour count DID show up eventually (though I counted, and the save file total was much less than the sum of the reported playtimes for each stage). But when I loaded it up again today, I noticed that the save file was back down to about 31 minutes or so - so somehow it LOST time.

**Comment by DracoOmega** [comment]
Oh, after exiting and restarting, now it's down to 8:32

**Comment by Kayinnasaki** [comment]
Yeah so it turned out it was resetting play time every load, so it was a straight forward fix.
