### ISSUE TITLE
Feedback: Monster encounter immediately after last Trevor chapter 1 checkpoint seems too brutal on reload

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#35]
I am prepared to be totally in the wrong here, if there's some good way to handle it that I haven't grasped (I'm not very good with Trevor), but the pit of skeletons combined with the bomb lobber and mage seems extremely hard for him to handle if you lack any mp for mobility options (which you won't, if you die and thus restart immediately before it). Depending on where bombs landed, it sometimes seemed extremely difficult to not just get knocked back into the pit and battered about repeatedly. (Trevor generally seems poorly-equipped to handle this kind of swarming without mp)

Maybe it could help to give him a few more mp drops before he has to cross that area? Like, just enough to perform SOME maneuver? (Though part of me wonders if, in general, he is the most handicapped of any character for not having mp, and ought to come back to life with just a little more in general - some of these moves seem a greater part of his normal gameplan than specials are for the others, since he's otherwise so slow to handle many things)

**Comment by Kayinnasaki** [comment]
Reduced the rate in which the Necromancer there acts. If thats not enough I'll put a lantern.
