### ISSUE TITLE
Graphics: Some blood effects are too high-res

### ISSUE THREAD

**Issue by Kishkish** [Kayinnasaki/BepIssueTracker#37]
Date: 2015.05.25

![bepblood01](https://cloud.githubusercontent.com/assets/12528330/7805619/4665bc56-032a-11e5-9cbd-ab65f4b8f547.png) ![bepblood02](https://cloud.githubusercontent.com/assets/12528330/7805620/4671f9ee-032a-11e5-98fd-d21ce2c25c8b.png)
![bepblood03](https://cloud.githubusercontent.com/assets/12528330/7805622/46751f0c-032a-11e5-9614-f0a85bce30c6.png) ![bepblood04](https://cloud.githubusercontent.com/assets/12528330/7805621/4673bdc4-032a-11e5-92b0-a2c0762b5b9c.png)
![bepblood05](https://cloud.githubusercontent.com/assets/12528330/7805623/46780b36-032a-11e5-8b6a-094417b1a1a2.png)

Evading pixel tax is a federal offense.

**Comment by Kayinnasaki** [comment]
Yeah lately I've been going in and fixing the resolution breaking blood effects on a number of enemies but I know some had to have leaked through, so if you spot any more let me know.
