### ISSUE TITLE
Sinlin chapter 4 boss powerup still messed up

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#38]
It's visible now! And both looks like gunner and tells you that you picked up gunner when you collect it, but somehow still gives you the bomber spell anyway.

(Incidentally, the fight seems an awful lot easier with gunner than bomber, as it turns out >.>)

**Comment by Kayinnasaki** [comment]
Ah, that was hiding another bug that has now been fixed!
