### ISSUE TITLE
Repeatedly die upon completion of Trevor chapter 1

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#39]
Twice in a row, after beating the manticore and having the 'chapter end' come up, the screen fades to black, then I hear the death sound effects and I am back at the previous checkpoint in that stage (and am unable to proceed to the next one).

**Comment by Kayinnasaki** [comment]
Fixed. if you wanna proceed, hit home and then end to beat the stage.
