### ISSUE TITLE
Large slowdown during Trevor stage 2 midstage dialog

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#42]
I don't know how helpful it is to report various specific slowdowns, but I sort I felt maybe there's some use if I report places where it's particularly bad, since maybe it highlights some code issue present there?

In any case, while Naomi and Trevor are chatting after the first basement segment, things slow way the heck down until a short while after the dialogue is concluded, at which point it suddenly speeds back up again (this change in framerate caused more than one pit-related death of mine, in fact...)

**Comment by Kayinnasaki** [comment]
Maybe fixed. I split level 5 up into two different maps (which should seem the same, playerwise, but helps clean things up). Going to leave open because I can figure some way to hopefully optimize the text code.

**Comment by Kayinnasaki** [comment]
I made one big optimization to the text code that, on my computer, tripled the FPS on the title screen. Probably will have lesser effects elsewhere, but I'm gonna mark this as closed. Feel free to resubmit this though if, next update, you find similar issues.
