### ISSUE TITLE
Survived fall in basement pit in Trevor stage 2

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#43]
In the basement segment right after the start, below the second bomb-lobber, it seems possible to land off-screen and walk around for quite a distance down there.

**Comment by Kayinnasaki** [comment]
This seems impossible, though I adjusted the kill plane just in case. Did you accidentally click-move in debug mode? That kills all kill planes until you restart/die.

**Comment by DracoOmega** [comment]
Uh, I suppose it's possible I did that by accident and never noticed, but the first time I fell down there, I could swear I walked further to the right and THEN the game decided it was time for me to die (but maybe I just hit an off-screen bat and was really low health at the time?). I guess I can't rule it out though (since it was only later on that I even noticed click-to-move was a thing - I almost submitted a camera bug due to it!)

**Comment by Kayinnasaki** [comment]
Weird! Well, I adjuted it so even if there was a next to impossible chance of it happening, its gone now. Maybe. Hopefully.
