### ISSUE TITLE
Typos and missing line breaks in 6 cutscene

### ISSUE THREAD

**Issue by muhgiddy** [Kayinnasaki/BepIssueTracker#45]
"You could ruin away. Start a life..."

Naomi's text is also missing some line breaks in a few places: http://puu.sh/iE94f/b637d86dca.png http://puu.sh/iE96x/d7a92671c8.png http://puu.sh/iE986/62b49f32f4.png

**Comment by Kayinnasaki** [comment]
Fixed and updated
