### ISSUE TITLE
Screen does not scroll after defeating Grand Faerie

### ISSUE THREAD

**Issue by TalentedJuli** [Kayinnasaki/BepIssueTracker#46]
![unexpected](https://cloud.githubusercontent.com/assets/13173892/8506676/b626129c-21d5-11e5-9dcf-25d4ec8345c5.jpg)

So after defeating the Grand Faerie, proceeding past the boss room does not cause the screen to scroll.  I ended up getting stuck down below the boss room and unable to find my way out the first time I beat her :(

**Comment by Kayinnasaki** [comment]
Fixed and update pending
