### ISSUE TITLE
(Naomi Stage 6) Archer in lower-left of 3rd room suddenly appears when moving beneath the stairs

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#50]
If you return to the left of the room, once you make it beneath the stairs (to pick up the shield powerup), the archer along the bottom-left doesn't appear until the camera can already see well beyond his position, causing him to suddenly appear out of nowhere.

**Comment by Kayinnasaki** [comment]
fixed/changed
