### ISSUE TITLE
Attempting to jump in confined spaces causes jump animation with no movement

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#53]
I first noticed this in the area where you get the dust striker powerup after the crumbling bridge in Naomi stage 6, but presumably there are other areas it can happen.

If there's no room to actually gain any height at all, pressing jump still cycles you through a complete jump animation, which looks really odd without any movement to go with it (like her legs are kind of spazzing out). Possibly the jump button should just do nothing at all, if no vertical movement is possible?

**Comment by Kayinnasaki** [comment]
Yeah, not really something worth the pain of fixing though.
