### ISSUE TITLE
(Naomi Stage 6) Curious timing behavior with crumbling bridge segment

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#54]
When Donovan lands on the bridge, only the segment immediately around him falls with his impact. If you don't continue moving onto the rest of the bridge, it will remain stable completely while the first part drops off the screen. The progressive crumbling only happens once the player's feet actually touch the rest of the bridge.

This means, among other things, that it is possible to leap over the first bit of the crumbling segment to give yourself a 'head start', as it still starts to crumbling from its rightmost edge, rather than where you land (which can be a decent bit beyond this). If you just kept walking rather than jump at this point, the timing for crossing the bridge is much, much meaner (maybe the intended timing? Though I admit that I hadn't actually worked out how to cross it consistently with so little window, until I discovered the 'easy' way....)

**Comment by Kayinnasaki** [comment]
I'm fine with this little cheat. :D
