### ISSUE TITLE
Typos in 'Game is closing because authorization failed'

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#55]
"beta _priveldges_ were revoked"
"everyone's _privledges_ were revoked"

Maybe the fact that the window popped up at all is _also_ a bug, but I tend to assume that it was maybe just an internet hiccup?

**Comment by Kayinnasaki** [comment]
Way to go me, but yeah don't worry too much about this, it's gonna get yanked out eventually ayways.
