### ISSUE TITLE
(Naomi Stage 6) Donovan lacks hitbox on rooftop attack (maybe intentional?)

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#56]
This might be intentional, but having Donovan HIMSELF land on you doesn't actually seem to inflict injury, as opposed to being hit by his spear dash after he lands.

**Comment by Kayinnasaki** [comment]
Yeah didn't want the player to accidentally get clipped in an awkward way. Intentional.
