### ISSUE TITLE
(Naomi stage 6) Assorted possible archer AI issues

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#57]
Archer in lower-right of 3rd screen appears to get 'stuck' at one point, if you stand on the right end of the stairs above it without immediately jumping down, and will vibrate in place, not even retreating from you after you jump down to confront it.

(Maybe intentional?) Archer who attacks downward from the upper platforms near the end of 2nd room (near the 3/4 powerup) will charge towards the player even once you reach level ground with it, unlike other archers' behavior, even attempting to collide with you directly.

(Maybe intentional) Archer beneath the stairs in the 3rd room stops firing upward when you stand on the lower dip of the stairs (near where the large knight is), and switches back to horizontal shots, even though it cannot possibly hit you that way from there.

(Unsure how to reproduce) Archer that fights alongside the gargoyle in the 3rd room, at some point switched to charging into me instead of retreating (only noticed after colliding with it once, at which point it kept switching positions to STAY inside of me)

**Comment by Kayinnasaki** [comment]
Intentional behaviors (well not really the vibrating but whatever)
