### ISSUE TITLE
(Naomi Stage 6) A few Vayn dialogue typos

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#59]
Pre-fight dialogue:
"All you see is a 'Filthy Daemon Whore." (missing the closing ')

Post-fight dialogue:
"The lynchpin of the ritual at the top of the bell tower." (possibly should have an 'is' before the 'at'?)
"It will quickly lose all the power its built up" (should be it's)

**Comment by Kayinnasaki** [comment]
fixed
