### ISSUE TITLE
(Naomi Stage 7) Died for no apparent reason after reaching the bell

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#62]
After reaching the bell itself, I jumped up onto it, got near the top, waited a couple seconds, and then dropped dead for no apparent reason. Neither the fire nor the demon was anywhere near me.

**Comment by Kayinnasaki** [comment]
fffffffffff I thought I figured this out and killed this bug. Are you sure you're running the most recent version? Try running the updater and see if it still happens.

**Comment by DracoOmega** [comment]
It's up to date, I'm afraid. Already updated just today before playing it, and the launcher doesn't want to update it any _more_ now, either.

**Comment by Kayinnasaki** [comment]
fixed

**Comment by DracoOmega** [comment]
I'm afraid I still had this happen again in the most recent version.

I reached the bell enough ahead of the demon that it didn't show up immediately. And then it didn't show up at _all_, even as the fire continued to rise, and then when the fire got somewhere near to the bottom of the bell (but perhaps not even quite that high yet), I spontaneously died. (This was on Beginner, in case that might somehow matter)

**Comment by Kayinnasaki** [comment]
If I'm reading this right, that's actually intentional. When the fire reaches a certain point, it triggers a death (partially because it can't cover the screen without causing problems). I at least changed it to a white fade out and removed animation changes so it looks less like a 'random death'.

**Comment by Kayinnasaki** [comment]
Oh also I'd recommend opening a new issue if something isn't fixed it's no big deal but it just makes it a bit easier for me to keep track of everything.
