### ISSUE TITLE
(Naomi Stage 7) Old Man flying hands can knock Naomi through the floor, trapping her there

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#64]
This happens quite frequently, and requires exiting the level afterward, as Naomi seems to get stuck behind the bell tower 'floor' and can't get up again.

It seems to happen MOST often when you're impacted directly from above (nearly 100%, in this case), though I've occasionally had it happen with a side-sweep, too. I assume it depends on the angle, and somehow the knockback is pushing you through the floor.

**Comment by Kayinnasaki** [comment]
SHOULD be fixed. Keep an eye out.
