### ISSUE TITLE
(Naomi Stage 7) Inconsistent behavior with Old Man hitbox

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#65]
The hitbox on the central man that allows you to actually damage the boss seems inconsistent.

For one thing, it's conspicuously impossible to hit it while riding a hand up, even when you land a swing that's obviously in range. Your swing just passes through without any feedback at all. It's unclear exactly how long you have to wait before he becomes damageable, and even if this is an intended mechanic (it seems theoretically fine if you can't get 'free' damage on the way up) I think there should absolutely be some kind of visual cue for when hits are going to 'count' and when they aren't. Maybe some kind of magic shield that gets temporarily shattered when the other hand sweeps through the boss, letting you damage him briefly then?

Worse, during at least one battle, the boss's hitbox just seemed not to activate at all for multiple hand passes. I kept doing exactly the same thing as always, and the boss just wasn't taking any damage. It did _eventually_ return to its normal behavior, though again without any indication of why.

**Comment by Kayinnasaki** [comment]
You can hit him, his hitbox is just his upperbody for balance reasons (which I guess isn't great but I got no reasonable way to make that less annoying)

**Comment by DracoOmega** [comment]
I guess I'll have to go back and test this again, since I was virtually _certain_ that hits would sometimes fail to register when well within the area that I am normally able to hit. But I guess I could have been totally imagining this somehow?
