### ISSUE TITLE
(Naomi Stage 7) Typos in dialogue before the bell tower descent

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#66]
Two of Naomi's lines seem to have a single ' at their start for no clear reason. (In fact, for a moment, I thought she was quoting/imitating someone, but then there's no closing ')

**Comment by Kayinnasaki** [comment]
` is used a command character for half line spacing. But I as dumb and put ' :(

But yeah, fixed. :D
