### ISSUE TITLE
(Naomi Stage 7) Belltower descent autoscroll shows curiously bloody Naomi falling Naomi

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#67]
Just a minor graphical glitch, but if you fall off the bottom of the screen, the camera will often catch up with you again and show Naomi having a typical bloody death animation, even though she clearly hasn't even hit any platform along the way. Apparently air pressure is exceptionally violent in this world.

(Maybe the camera could just stop scrolling when you die?)

**Comment by Kayinnasaki** [comment]
Well changed the death animation to be way more suddens so hopefully that doesn't come up again.
