### ISSUE TITLE
(Naomi Stage 7) Donovan's slow-walk-spear-slash ignores ramps

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#69]
If Donovan uses the attack where he takes a few slow steps forward and abruptly slashes with his spear while he is on one of the elevated edges of the battlefield, he will (at least some of the time) walk straight out onto open air rather than descend the ramp, and only fall back down to the ground after the attack is complete.

**Comment by Kayinnasaki** [comment]
fixed
