### ISSUE TITLE
(Naomi Stage 7) Visual glitch with Donovan's dash animation while you're dead

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#70]
While the player's death animation is playing, the copies of Donovan trailing him during his dash animation get scaled extremely tall (probably wider than normal, too?) which looks very bizarre. There might be something else wrong with it, too, but that was the most obvious.

For a while, I actually assumed it was some new attack he was demonstrating, until it never happened while I was _alive_.

**Comment by Kayinnasaki** [comment]
fixed (shadow removed during death animation)
