### ISSUE TITLE
(Naomi Stage 7) Inconsistent damage required to break second Donovan ground-wave-spam attack?

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#71]
This might be me just not fully understanding the mechanics of the fight at this point, but while a single hit was always sufficient to get Donovan to end his first ground-wave-spam attack and resume normal battle, the second time he does this would _often_ be ended with a single hit, but sometimes he would take 2 or 3 and still remain in the corner, firing projectiles (and it's obviously a lot more dangerous to make lunging attacks at him if you can't know whether they will knock him out of that attack or not).

**Comment by Kayinnasaki** [comment]
fixed
