### ISSUE TITLE
(Naomi Stage 7) Lethal fall distance in belltower descent feels inconsistent

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#72]
I'm afraid I can't be specific here yet (would need to go back and test it some more later), but it felt like sometimes I would die on relatively short falls, and other times live through much longer ones to land on some platform beneath the bottom of the screen. Given that the player can know in advance (on repeat attempts) where platforms below them ARE, it's a bit undesirable if it's inconsistent whether jumping down to one will land you safely, or kill you.

Possibly it should NEVER be possible here to land on a platform that cannot be currently seen on the screen, as this is the most predictable behavior from the player's perspective? Not certain.

**Comment by Kayinnasaki** [comment]
It's a fixed distance. I purposefully give a bit of mercy with the height because I never want the player to feel cheated.

**Comment by DracoOmega** [comment]
Is this a fixed distance below the bottom of the screen before triggering your death, or a fixed distance from where you first start _falling_?

**Comment by Kayinnasaki** [comment]
Below the bottom of the screen
