### ISSUE TITLE
Lightning effect causing permanent darkness in Vayn intro

### ISSUE THREAD

**Issue by muhgiddy** [Kayinnasaki/BepIssueTracker#73]
Happened right after respawning to fight Vayn http://puu.sh/lPUkh/08cd586c4f.png . Only happened the one time, not sure what I did differently.

**Comment by Kayinnasaki** [comment]
Did you die? Dod you use special to try and skip some of the cutscene? Any other little details?

**Comment by muhgiddy** [comment]
I died eventually, but nothing around the time it happened. Wasn't doing anything special as far as I remember, just spawned after dying to Vayn, thing happened and I could still move around with everything black just fine. It went away at the start of the fight.

**Comment by Kayinnasaki** [comment]
Should be fixed!
