### ISSUE TITLE
Hardlock by pausing during Old Man intro

### ISSUE THREAD

**Issue by muhgiddy** [Kayinnasaki/BepIssueTracker#74]
Hit start a little early during the Old Man intro and screen was locked to this http://puu.sh/lQOjH/cdb95f8913.png . No buttons did anything, not even the debug ones. Had to restart BEP and lost all progress made in the session.

**Comment by Kayinnasaki** [comment]
Unrelated to that, did the game not save your progress? D: That'd also be a bug.

**Comment by muhgiddy** [comment]
Yeah all my progress was gone. Had to do 6 and 7 over again.

**Comment by Kayinnasaki** [comment]
Both bugs should be fixed in the next release.
