### ISSUE TITLE
Various typos

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#76]
Faerie bestiary entry:
"Faeries, like other constructs exist" (missing , after constructs)

Naomi stage 2 victory cutscene:
Naomi has a superfluous leading ' at the start of the dialog containing "I wouldn't have been sent on this mission if I wasn't capable"

Naomi stage 4 boss conversation:
"I'm getting really sick [of] everyone telling me what to do." (missing of)
"You embrace this new age and it's sinful magic!" (it's should be its)
"You worship a false idol, whom brought this cursed world on us." (Pretty sure 'whom' is incorrect here and should be 'who'. Stylistically, I also think 'on' should also be 'upon', here.)
"You are blind fools, but us Wise Men when turn his power against him." (when probably should be will?)

**Comment by Kayinnasaki** [comment]
fixed
