### ISSUE TITLE
(Naomi Stage 3) Fire mysteriously rains down from above

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#77]
In the first room with the bombardier plants, if you idle around a little while for whatever reason (even some trouble dealing with the monsters might do it), fire slowly starts raining down from the top of the screen, somewhere near the middle.

This is almost certainly coming from faeries in Sinlin's area which is 'above' that room, and whose projectiles are slowly closing the great distance, but I really don't think their projectiles should be crossing over into this area, especially since the source is otherwise inscrutable and there's a considerable delay before they show up at all.

**Comment by Kayinnasaki** [comment]
Also can't recreate. Any particular spot/difficulty?

**Comment by DracoOmega** [comment]
Curiously, I can't seem to recreate this myself now, either, although I've seen it occur multiple times in the same area, on different difficulties (standard and beginner, at least), in different versions of the game (including the one I'm currently testing).

(And I just tested whether it's something that only happens if you remove the killplanes in debug mode, and that doesn't seem to cause it either). I guess I'll just keep an eye out if I can figure out what circumstances trigger it?

**Comment by Kayinnasaki** [comment]
Closing for now, but feel free to file a new bug on the same topic if you encounter it again with more information.
