### ISSUE TITLE
(Naomi Stage 3) Bit of terrain in first bombardier plant room slightly misaligned

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#78]
In the first bombardier plant room, the little spur of land just after the second pit filled in on Beginner appears to be a single pixel lower than all the other terrain its supposedly aligned with. This isn't really noticeable on other difficulties, but since you can walk across the whole section on Beginner, it causes Naomi to visibly stumble at this point, for reasons that are unclear unless you look really closely (I actually have to zoom in a screenshot to be sure what was going on)

**Comment by Kayinnasaki** [comment]
Vaguely fixed. Moved the blocks down more to make it a pseudo pit that feels less glitchy.

**Comment by DracoOmega** [comment]
Is there actually some reason that one island is a pixel lower than the other then, just out of curiosity?

**Comment by Kayinnasaki** [comment]
This is one of those cargo cult things here I am totally not sure why but assume I had a reason. It isn't actually an easy thing to do on accident.
