### ISSUE TITLE
(Naomi Stage 4) Can leap through manticore and reach buggy area

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#79]
At least on Beginner, you can leap into the manticore as it knocks your platform down, and just walk on through it. Knockback likely makes this hard on other difficulties, but it might still be possible to manage it somehow? (I haven't really tried yet).

Once you are secure on the platform, the manticore (predictably) sits there passively, and can be attacked for apparent 'damage', though no effect. But more relevantly, if you walk forward until you reach the end of the platform, leaping into the air causes you to be repulsed backwards by an invisible force, and then you instantly die for no reason.

**Comment by Kayinnasaki** [comment]
pushback made fair more aggressive.
