### ISSUE TITLE
Strange tinking sounds at the base of several staircases

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#81]
Holding up near the base of several specific staircases will rapidly produce the same tink sound as striking something that is immune to damage, until holding the button moves you a little bit further up the staircase and away from the point at which the sound effect triggers. This is easily reproducible, though only at specific locations.

Ones I have noticed so far:
- Naomi stage 4, base of highest staircase in small area with Vayn / Donovan conversation
- Naomi stage 7, belltower ascent, base of first staircase that rises right to left after the point at which the belltower first narrows
- Naomi stage 7, base of final stairs before Old Man boss

**Comment by Kayinnasaki** [comment]
whoops, sound I was using for debugging. Fixed.
