### ISSUE TITLE
(Naomi Stage 7) Game rapidly produces impact noises when dying to fall damage in belltower descent

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#82]
When you die by falling off the bottom of the screen in the burning belltower descent, a bunch of impact noises are played, though the exact frequency seems to depend upon _something_ I haven't figured out - but notably, this frequency is sometimes so high that it sounds like the game is loudly freaking out about something.

**Comment by Kayinnasaki** [comment]
fixed
