### ISSUE TITLE
Advanced difficulty still claims to be using lives, but implementation seems buggy

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#83]
I don't know if it's _intended_ that Advanced use a limited lives system, unlike the rest of the game, but even if it is, the implementation is buggy.

Text at the bottom of the screen lists lives and chapter by number, instead of chapter name like other difficulties. When I lost my last life, I did get a gameover screen, but pressing 'retry stage' just tossed me back to the stage select like normal, re-selecting the same stage loaded me up at the very same checkpoint I'd died at, only now I had 0 lives in reserve so that _every_ death repeated this (though, effectively, I was still restarting freely at checkpoints like in every other difficulty)

(Also, 'restart stage' caused the boss music to continue playing on the level select screen, while the level select music was _also_ playing, and picking 'exit to main menu' had the camera slightly to the right of normal, such that the edge of the options menu was visible on the start screen)

**Comment by Kayinnasaki** [comment]
Yeah definitely don't wanna force lives for advanced. That'd be a bit much. Fixed.
