### ISSUE TITLE
(Naomi Stage 3) Restarting from post-Sinlin/Vayn segment allows you to retrigger scene

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#84]
If you reach the checkpoint after the segment where you have to deal with Vayn while Sinlin runs ahead ("Still following me?"), then die, then go _backwards_ from where you restart after dying, Sinlin and Vayne will still be back where you last met them, triggering Sinlin's dialog and movement once more.

**Comment by Kayinnasaki** [comment]
Moved spawn to avoid backtracking.
