### ISSUE TITLE
(Debug Mode) Using click-to-move screws up death pits for the rest of that life

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#85]
If you reposition the character with the mouse in debug mode, then even after you turn debug mode _off_ again, pits will no longer kill the character until you either die or exit the stage. This doesn't happen merely from toggling debug mode, but only specifically after using click-to-move.

(This sent me on some extended wild goose chases over pit-related weirdness that I couldn't figure out how to properly reproduce.... >.>)

**Comment by Kayinnasaki** [comment]
This is intended behavior, though it can be annoying at times. Zipping around and hitting into kill planes is a real problem. When testing for gaps, be sure to do so out of debug mode to be safe.

**Comment by DracoOmega** [comment]
My point is that even when you _exit_ debug mode again, the invulnerability persists until you actually die or leave the level. (And that probably turning debug mode off should remove this invulnerability)

(It is unfortunately easy to forget whether you used that feature at some point in the current life, which could have been many screens back)

**Comment by Kayinnasaki** [comment]
Yeah unfortunately that doesn't quite work with how simple the implementation of the click to move thing works. It doesn't make you invlunerable, it literally kills all the kill planes. A bit of a pain, but not gonna fret over a debug feature too much.

**Comment by DracoOmega** [comment]
Oh, sure. Always hard to tell from the outside the difference between 'Add a single line of code that sets something to false' and something way more onerous to change.
