### ISSUE TITLE
(Naomi Stage 2: Advanced) Bomb lobber attacks you before the level intro is fully loaded

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#86]
There is a bomb lobber at the checkpoint before the longer rafting segment, and he will consistently leap into the player before the level title is finished displaying (sort of appearing to get stuck in a block while doing so, in fact). It _is_ Advanced, so maybe it's okay to have something attack you before 'loading' is finished, but it felt awkward to me, graphical glitches aside.

(On reflection, these monsters seem able to act before things are fully loaded, in general. Maybe other monsters also can, but it's more noticeable with them, as I recall seeing bombs already lying on the ground in some places before the level was loaded enough to see them throw them. It just never mattered much, since they didn't spawn _right on top of the player_.)

**Comment by Kayinnasaki** [comment]
fixed the situation so you can't get hit.
