### ISSUE TITLE
Slightly odd interaction between lobbed bombs and candles

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#87]
Maybe not a 'bug', per se, but unexpected behavior that did result in my death a couple times, so I figured I'd report it. (Then again, it was on Advanced, so maybe it's intentional...)

If a lobbed bomb hits a candle in mid-flight, it will destroy the candle and then immediately detonate, but (because there is no surface beneath it, unlike all other situations where they detonate), the explosion falls swiftly with gravity, covering a very large screen area with surprising speed.

**Comment by Kayinnasaki** [comment]
I have been unable to recreate this. Is there a spot where this happens a lot?

**Comment by DracoOmega** [comment]
On further examination, I may have misunderstood the cause, but the place I saw it demonstrated several times was the lobber just after the Naomi stage 2 Advanced checkpoint that has a lobber next to it. The lobber just past the floating platform with the fire elemental.

But now I am thinking, rather than the candle, it may somehow happen when the lobbed bomb hits the _ceiling_? Definitely several times there it abruptly produced a falling detonation, though I can't always reproduce it (it did kill me at least twice, though!)

**Comment by Kayinnasaki** [comment]
Getting caught in the roof seems likely. I'll take a look at that.

**Comment by Kayinnasaki** [comment]
stopped the bouncing explosion so even though I couldn't quite recreate this, it shouldn't be an issue in the future.
