### ISSUE TITLE
(Sinlin Stage 4) Phantasmagoria lower-platform flame attack continues to occur while paused

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#93]
Even if the game is paused, the lower platforms will periodically show the flame wave warning sign, and then the flame wave itself moving along them (at a reduced height). The delay between appearances seemed roughly around what you would expect for this attack if the game was NOT paused.

Standing in the wave would not actually cause you to take damage if you remained paused until it went away, but if you _unpaused_ while the flames were still there, you would immediately be hit by them, and take damage as normal.

**Comment by Kayinnasaki** [comment]
Should be fixed now due to changes in pause code
