### ISSUE TITLE
(Sinlin Stage 2) Chakram won't hit stationary bat?

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#94]
The second bat (on advanced) past where you pick up the chakram spell can be hit with it from long range, but the projectiles appear to pass cleanly through the center of its body until you get close enough to wake it up (when you can now hit it like normal). This applies to both the normal chakrams AND the laser (and thus probably other weapons).

Interestingly, there are some other bats here that CAN be hit by the laser from further away than they wake up. It's possible the trigger distance is somewhere not _quite_ close enough to wake them up, but terrain for this bat prevents you from getting a good shot at that distance, without getting even closer?

**Comment by Kayinnasaki** [comment]
What area is this? I'm guessing the bat isn't actually active yet so I probably just need to adjust the activation range.

**Comment by DracoOmega** [comment]
It's this one (by the chakram), just a little past the first checkpoint:

![bep_bug4](https://cloud.githubusercontent.com/assets/12538566/12539637/4054337a-c2d2-11e5-9fc9-5fd874a34b00.png)

**Comment by Kayinnasaki** [comment]
fixed
