### ISSUE TITLE
(Trevor Stage 1) Sword charge can get stuck at 0% after intro cutscene?

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#95]
Can't really explain or easily reproduce this one, but after seeing the stage 1 level intro cutscene, when I landed, my charge was permanently stuck at 0% (and also colored red). It was now impossible to actually attack at all - pressing the attack button did nothing. I saw no way to reverse this, short of dying/exiting.

**Comment by Kayinnasaki** [comment]
Should be fixed in the next version (Along with SInlen starting with weapons based off of Naomi's last weapon)
