### ISSUE TITLE
(Naomi Stage 6) Gargoyle ground wave gets stuck in floor, does not expire

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#98]
This happened with the first gargoyle near the beginning of the stage. It can probably happen with others, but the terrain here is probably more suited to it.

The ground wave flew through the air and hit the left side of the platform with stairs (from slightly beneath that platform), and then traveled _into_ that wall for a short distance before getting stuck there. It then remained there, without moving or expiring (continuing to animate), and was close enough to the ground to hit the player as they tried to walk up the stairs.

**Comment by DracoOmega** [comment]
Attached a screenshot, since I had one (the stationary wave is the one to the right of Naomi, if that is unclear)

![bep_bug3](https://cloud.githubusercontent.com/assets/12538566/12538674/fd9cd0d6-c2b9-11e5-83a9-caffcdefd32a.png)

**Comment by Kayinnasaki** [comment]
Should be fixed.
