### ISSUE TITLE
(Naomi Stage 5) Knife-thrower leaps backwards into wall, travels through it

### ISSUE THREAD

**Issue by DracoOmega** [Kayinnasaki/BepIssueTracker#99]
The knife-thrower immediately after the first checkpoint in stage 5 (advanced) did a normal backwards leap into some stairs, then got stuck in the wall, rapidly vibrated her way rightward until she came out the other side, then fell free of it.

**Comment by Kayinnasaki** [comment]
Should stay in bounds now. They might still get caught and act a little strange and that's fine, but they shouldn't break physics. Be aware of any unexpected changes elsewhere due to their new collision check.
